### ISSUE TITLE
TextReader.ReadLine and TextWriter.WriteLine seems to be ignored

### ISSUE THREAD

**Issue by hazzik** [maca88/AsyncGenerator#167]
I'm trying to generate async code for one of my libraries. The main 'asyncable' methods are TextReader.ReadXXX and TextWriter.WriteXXX, but they seem to be ignored. 

The code is here: https://github.com/hazzik/qif/commit/709d4bf68c248b362a67e22f2bd0f6d939cc39ec

**Comment by maca88** [comment]
You need to set the method conversion to `Smart` in order scan method bodies for invocations with async conterparts. You can use the following configuration, which will scan all method bodies in the project:
```
projects:
- filePath: QifApi/QifApi.csproj
  targetFramework: net461
  concurrentRun: true
  applyChanges: true
  analyzation:
    methodConversion:
    - conversion: Smart
      all: true
    callForwarding: true
    cancellationTokens:
      enabled: true
      guards: true
    scanMethodBody: true
    scanForMissingAsyncMembers:
    - all: true
```
