### ISSUE TITLE
Invalid code generated for newType conversion when ignoring a method

### ISSUE THREAD

**Issue by fredericDelaporte** [maca88/AsyncGenerator#42]
Scenario: a test fixture having its async version generated as a new type. It contains some utility methods for setup and tear-down, methods for which we have no interest in having async counterparts.

Not ignoring them causes the generated async class to contain both the sync and the async version, with the async version usually not used. (Minor nuisance.)
Ignoring them causes the generated async class to not contain the method at all, causing its setup and/or tear-down method to not compile due to missing the sync version of the utility method.

So there is an easy workaround, just not ignore them. Now if we were really needing to ignore a specific method in such case, we would have troubles.

Minimal example:

```C#
using System.Data.Common;
using System.Data.SqlClient;

namespace TestClass
{
    public class BaseClass
    {
        public virtual void Setup()
        {

        }
    }

    public class Class1 : BaseClass
    {
        public override void Setup()
        {
            RunSetup();
        }

        public void RunSetup()
        {
            using (var c = new SqlConnection(""))
            {
                c.Open();
            }
        }

        public void Do()
        {
            DbConnection c = null;
            c.Open();
        }
    }
}
```

With

```
projects:
- filePath: TestClass\TestClass.csproj
  concurrentRun: true
  applyChanges: true
  analyzation:
    methodConversion:
    - conversion: ToAsync
      name: Do
      containingTypeName: Class1
    - conversion: Ignore
      name: RunSetup
    typeConversion:
    - conversion: NewType
      name: Class1
    - conversion: Ignore
      name: BaseClass
    scanMethodBody: true
    scanForMissingAsyncMembers:
    - all: true
```

**Comment by maca88** [comment]
There is also a [Copy](https://github.com/maca88/AsyncGenerator/blob/master/Source/AsyncGenerator.Core/MethodConversion.cs#L34) conversion that will copy the method to the new type. So the below settings should work:
```
methodConversion:
    - conversion: ToAsync
      name: Do
      containingTypeName: Class1
    - conversion: Copy
      name: RunSetup
```
But I agree that the generator should be smart enough to override the user settings (Ignore -> Copy) with a warning so the code would compile.
