### ISSUE TITLE
Lacking inherited type generation for newType conversion

### ISSUE THREAD

**Issue by fredericDelaporte** [maca88/AsyncGenerator#43]
Scenario: a base test fixture class defines some settings altering the way all its tests are run. A bunch of other classes inherits that base class and only alters its settings, not containing directly themselves any method to be converted to async. The base test fixture class has its async counterpart generated as a new type.

Expected result: new types are also generated for descendant classes, allowing to have their async counterparts.

But they are not generated.

Minimal example:

```C#
using System.Data.Common;
using System.Data.SqlClient;

namespace TestClass
{
    public class BaseClass
    {
        public virtual void Setup()
        {

        }
    }

    public class Class1 : BaseClass
    {
        public virtual bool SomeSetting => false;

        public override void Setup()
        {
            RunSetup();
        }

        public void RunSetup()
        {
            if (SomeSetting)
                using (var c = new SqlConnection(""))
                {
                    c.Open();
                }
        }

        public void Do()
        {
            DbConnection c = null;
            c.Open();
        }
    }

    public class Class2 : Class1
    {
        public override bool SomeSetting => true;
    }
}
```

With conf
```
projects:
- filePath: TestClass\TestClass.csproj
  concurrentRun: true
  applyChanges: true
  analyzation:
    methodConversion:
    - conversion: ToAsync
      name: Do
      containingTypeName: Class1
    typeConversion:
    - conversion: NewType
      name: Class1
    - conversion: NewType
      name: Class2
    - conversion: Ignore
      name: BaseClass
    scanMethodBody: true
    scanForMissingAsyncMembers:
    - all: true
```

Concrete NHibernate case [here](https://github.com/fredericDelaporte/nhibernate-core/blob/NH-2176/src/NHibernate.Test/NHSpecificTest/NH3023/DeadlockConnectionPoolIssueTest.cs#L296) by example. (Note that adding [TextFixture] attribute on the class does not help. This is another trouble by the way, needing to be fixed on NHibernate side : `TextFixture` attribute is almost obsolete, NUnit does not need it anymore and many fixtures do not have it already. This causes current NHibernate.Test rules to not generate async tests for those fixtures, like for NH-4004 currently in master.)

**Comment by maca88** [comment]
Now derived types will be generated as new types if their conversion is not set (`Unknown`) and there exist at least one async member in one of the base types.
The current problem for the NHibernate project is that the type conversion is set for all types for the test project . One way is to set the type conversion to `NewType` for all types that derive from `TestCase:`
```
    typeConversion:
    - conversion: Ignore
      name: NorthwindDbCreator
    - conversion: Ignore
      name: ObjectAssert
    - conversion: Ignore
      name: LinqReadonlyTestsContext
    - conversion: Ignore
      name: TestCase
    - conversion: Ignore
      hasAttributeName: IgnoreAttribute
    - conversion: NewType
      anyBaseTypeRule: IsTestCase
```
But currently with this setting the bug that you [recently reported](https://github.com/maca88/AsyncGenerator/issues/44) occurs.

**Comment by maca88** [comment]
After bypassing the [issue](https://github.com/maca88/AsyncGenerator/issues/44) by commenting the problematic mapping (thanks for the info) there are a lot of errors with the generated code so will reopen this issue until all errors are fixed.

**Comment by fredericDelaporte** [comment]
I guess current NHibernate test project rational for putting `Ignore` on all class derived from `TestCase` but those having `TestFixture` is to minimize async code generation.
So instead of changing configuration we could add this attribute on derived classes which are actually fixtures.
Doing that allows to generates the missing classes when using an AsyncGenerator compiled from current sources, and the NHibernate test project still compiles.

**Comment by maca88** [comment]
Another option is to check if any of the base types has the TestFixture attribute:
```
    typeConversion:
    - conversion: Ignore
      name: NorthwindDbCreator
    - conversion: Ignore
      name: ObjectAssert
    - conversion: Ignore
      name: LinqReadonlyTestsContext
    - conversion: Ignore
      hasAttributeName: IgnoreAttribute
    - conversion: NewType
      hasAttributeName: TestFixtureAttribute
    - conversion: NewType
      anyBaseTypeRule: HasTestFixtureAttribute
    - conversion: Ignore
      rule: IsTestCase
    - conversion: Ignore
      anyBaseTypeRule: IsTestCase
```
where the type rule `HasTestFixtureAttribute` is defined like this:
```
- filters:
  - hasAttributeName: TestFixtureAttribute
  name: HasTestFixtureAttribute
```
with this we can mark only the base classes with `TestFixture` attribute and the all derived classes will be also converted.
With this settings the current generator produces a valid code.

**Comment by maca88** [comment]
The errors are now fixed and to generate all available tests I used this type conversion:
```
    typeConversion:
    - conversion: Ignore
      name: NorthwindDbCreator
    - conversion: Ignore
      name: ObjectAssert
    - conversion: Ignore
      name: LinqReadonlyTestsContext
    - conversion: Ignore
      name: TestCase
    - conversion: Ignore
      hasAttributeName: IgnoreAttribute
    - conversion: NewType
      hasAttributeName: TestFixtureAttribute
    - conversion: NewType
      anyBaseTypeRule: HasTestFixtureAttribute
    - conversion: NewType
      anyBaseTypeRule: IsTestCase
```
where the rule `HasTestFixtureAttribute` is the same as in the previous comment.
